//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressHouse
    {
        public int IDAdressHouse { get; set; }
        public Nullable<int> IDHouse { get; set; }
        public Nullable<int> IDAddress { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual House House { get; set; }
    }
}
