//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DuAn()
        {
            this.AddressDuAns = new HashSet<AddressDuAn>();
            this.Houses = new HashSet<House>();
            this.ImageDuAns = new HashSet<ImageDuAn>();
            this.InfoDuAns = new HashSet<InfoDuAn>();
        }
    
        public int IDDuAn { get; set; }
        public Nullable<int> Block { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> House { get; set; }
        public string Sumary { get; set; }
        public Nullable<int> IDInvestor { get; set; }
        public string IDMap { get; set; }
        public Nullable<byte> State { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }
        public string GiaBan { get; set; }
        public string GiaThue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressDuAn> AddressDuAns { get; set; }
        public virtual Investor Investor { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<House> Houses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageDuAn> ImageDuAns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoDuAn> InfoDuAns { get; set; }
    }
}
