//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoHouse
    {
        public int IDInfoHouse { get; set; }
        public Nullable<int> IDHouse { get; set; }
        public Nullable<int> IDKey { get; set; }
        public string Value { get; set; }
    
        public virtual House House { get; set; }
        public virtual Key Key { get; set; }
    }
}
