//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Key()
        {
            this.InfoDuAns = new HashSet<InfoDuAn>();
            this.InfoHouses = new HashSet<InfoHouse>();
        }
    
        public int IDKey { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Required { get; set; }
        public string Type { get; set; }
        public Nullable<int> IDCategory { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoDuAn> InfoDuAns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoHouse> InfoHouses { get; set; }
    }
}
